name:                sand
version:             0.1.0.0
github:              "githubuser/sand"

description:         Please see the README on GitHub at <https://github.com/githubuser/sand#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  sand-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sand
    - hspec
